title: Sai Vivek Alli # your name (or website title) here
logo: "/images/photo-output.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  With over five years of experience as a Data Engineer and Analyst, I bring expertise in building real-time data pipelines and optimizing data workflows 
  with tools like SQL, Python, AWS, and Azure. Specializing in ETL, data visualization, and machine learning, I transform complex data into actionable insights. 
  My skills in using Databricks, Power BI, and cloud technologies ensure I can enhance any company's data processing capabilities and drive informed decision-making.  
  <br><br>
  <a href="https://www.linkedin.com/in/sai-vivek-alli-7b1831172/">LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here


